api_version: v1alpha1
kind: LocalData
spec: 
  name: trino_tpch
  connection_options: 
    Trino:
      user: trino
      password: '' #<-- Note that this is the environment variable that will hold the password, not the plaintext password itself
      host: localhost
      port: "8080"
      secure: false
  data_sources:
    - name: tpch.tiny.lineitem
      source_sql: |
        select *, 
        extendedprice/quantity as unitprice, 
        tax*extendedprice as tax_amount 
        from tpch.tiny.lineitem
      source_options: 
        Trino: {}
      fields:
        - name: tax_amount
          path: tax_amount
        - name: unitprice
          path: unitprice
        - name: linenumber
          path: linenumber
        - name: partkey
          path: partkey
        - name: suppkey
          path: suppkey
        - name: orderkey
          path: orderkey
        - name: quantity
          path: quantity
        - name: extendedprice
          path: extendedprice
        - name: discount
          path: discount
        - name: tax
          path: tax
        - name: commitdate
          path: commitdate
        - name: receiptdate
          path: receiptdate
        - name: returnflag
          path: returnflag
        - name: linestatus
          path: linestatus
        - name: shipdate
          path: shipdate
      default_permission:
        allowed_columns:
          - tax_amount
          - unitprice
          - linenumber
          - partkey
          - suppkey
          - orderkey
          - quantity
          - extendedprice
          - tax
          - discount
          - linestatus
          - returnflag
          - shipdate
        allowed_rows: returnflag='N'
    - name: tpch.tiny.customer
      source_sql: tpch.tiny.customer
      source_options: 
        Trino: {}
      fields:
        - name: custkey
          path: custkey
        - name: name
          path: name
        - name: address
          path: address
        - name: nationkey
          path: nationkey
        - name: phone
          path: phone
        - name: acctbal
          path: acctbal
        - name: mktsegment
          path: mktsegment
        - name: comment
          path: comment
      default_permission:
        allowed_columns:
          - custkey
          - name
          - nationkey
          - acctbal
          - mktsegment
          - comment
        allowed_rows: acctbal>0
    - name: tpch.tiny.orders
      source_sql: tpch.tiny.orders
      source_options: 
        Trino: {}
      fields:
        - name: orderkey
          path: orderkey
        - name: custkey
          path: custkey
        - name: orderstatus
          path: orderstatus
        - name: totalprice
          path: totalprice
        - name: orderdate
          path: orderdate
        - name: orderpriority
          path: orderpriority
        - name: clerk
          path: clerk
        - name: shippriority
          path: shippriority
        - name: comment
          path: comment
      default_permission:
        allowed_columns:
          - orderkey
          - custkey
          - orderstatus
          - totalprice
          - orderdate
          - orderpriority
          - clerk
          - shippriority
          - comment
        allowed_rows: "true"

