FROM rust:1.76.0-bullseye as scheduler
RUN apt-get update && apt-get install -y protobuf-compiler
RUN cargo install ballista-scheduler
ENTRYPOINT ["ballista-scheduler"]

FROM rust:1.76.0-bullseye as executor
RUN apt-get update && apt-get install -y protobuf-compiler
RUN cargo install ballista-executor
ENTRYPOINT ["ballista-executor"]