FROM rust:1.73.0 as scheduler
RUN apt-get update && apt-get install -y protobuf-compiler
RUN cargo install --locked ballista-scheduler
ENTRYPOINT ["ballista-scheduler"]

FROM rust:1.73.0 as executor
RUN apt-get update && apt-get install -y protobuf-compiler
RUN cargo install --locked ballista-executor
ENTRYPOINT ["ballista-executor"]