api_version: v1alpha1
kind: RemoteMapping
spec:
  entity_name: lineitem
  mappings:
    - relay_name: na_data_relay
      remote_entity_name: lineitem
      relay_mappings:
        - local_info: unitprice
          info_mapped_name: unitprice  
        - local_info: linenumber
          info_mapped_name: linenumber
        - local_info: partkey
          info_mapped_name: partkey
        - local_info: suppkey
          info_mapped_name: suppkey
        - local_info: orderkey
          info_mapped_name: orderkey
        - local_info: quantity
          info_mapped_name: quantity
        - local_info: extendedprice
          info_mapped_name: extendedprice
        - local_info: discount
          info_mapped_name: discount_percent
          transformation:
              other_to_local_info: "{v} / 100"
              replace_from: "{v}"
        - local_info: tax
          info_mapped_name: tax_percent
          transformation:
              other_to_local_info: "{v} / 100"
              replace_from: "{v}"
        - local_info: commitdate
          info_mapped_name: commitdate
        - local_info: receiptdate
          info_mapped_name: receiptdate
        - local_info: returnflag
          info_mapped_name: returnflag
        - local_info: linestatus
          info_mapped_name: linestatus
        - local_info: shipdate
          info_mapped_name: shipdate
    - relay_name: emea_data_relay
      remote_entity_name: lineitem
      sql: select *, extendedprice/quantity as unitprice from lineitem
      relay_mappings:
        - local_info: unitprice
          info_mapped_name: unitprice  
          literal_derived_field: true
        - local_info: linenumber
          info_mapped_name: linenumber
        - local_info: partkey
          info_mapped_name: partkey
        - local_info: suppkey
          info_mapped_name: suppkey
        - local_info: orderkey
          info_mapped_name: orderkey
        - local_info: quantity
          info_mapped_name: quantity
        - local_info: extendedprice
          info_mapped_name: extendedprice
        - local_info: discount
          info_mapped_name: discount
        - local_info: tax
          info_mapped_name: tax
        - local_info: commitdate
          info_mapped_name: commitdate
        - local_info: receiptdate
          info_mapped_name: receiptdate
        - local_info: returnflag
          info_mapped_name: returnflag
        - local_info: linestatus
          info_mapped_name: linestatus
        - local_info: shipdate
          info_mapped_name: shipdate
    - relay_name: apac_data_relay
      remote_entity_name: lineitem
      sql: select *, extendedprice/quantity as unitprice from lineitem
      relay_mappings:
        - local_info: unitprice
          info_mapped_name: unitprice  
          literal_derived_field: true
        - local_info: linenumber
          info_mapped_name: linenumber
        - local_info: partkey
          info_mapped_name: partkey
        - local_info: suppkey
          info_mapped_name: suppkey
        - local_info: orderkey
          info_mapped_name: orderkey
        - local_info: quantity
          info_mapped_name: quantity
        - local_info: extendedprice
          info_mapped_name: extendedprice
        - local_info: discount
          info_mapped_name: discount
        - local_info: tax
          info_mapped_name: tax
          transformation:
            other_to_local_info: "({v} + 1) * .05"
            replace_from: "{v}"
        - local_info: commitdate
          info_mapped_name: commitdate
        - local_info: receiptdate
          info_mapped_name: receiptdate
        - local_info: returnflag
          info_mapped_name: returnflag
        - local_info: linestatus
          info_mapped_name: linestatus
        - local_info: shipdate
          info_mapped_name: shipdate
    - relay_name: offline_data_relay
      remote_entity_name: lineitem
      relay_mappings:
        - local_info: unitprice
          info_mapped_name: unitprice  
        - local_info: linenumber
          info_mapped_name: linenumber
        - local_info: partkey
          info_mapped_name: partkey
        - local_info: suppkey
          info_mapped_name: suppkey
        - local_info: orderkey
          info_mapped_name: orderkey
        - local_info: quantity
          info_mapped_name: quantity
        - local_info: extendedprice
          info_mapped_name: extendedprice
        - local_info: discount
          info_mapped_name: discount
        - local_info: tax
          info_mapped_name: tax
          transformation:
            other_to_local_info: "({v} + 1) * .05"
            replace_from: "{v}"
        - local_info: commitdate
          info_mapped_name: commitdate
        - local_info: receiptdate
          info_mapped_name: receiptdate
        - local_info: returnflag
          info_mapped_name: returnflag
        - local_info: linestatus
          info_mapped_name: linestatus
        - local_info: shipdate
          info_mapped_name: shipdate

