api_version: v1alpha1
kind: PeerRelay
spec:
  name: global_data_relay
  rest_endpoint: "https://localhost:9443"
  flight_endpoint: "https://localhost:51051"
  x509_cert_file: ./deploy/development/global_data_relay/client_cert.pem
---
api_version: v1alpha1
kind: PeerRelay
spec:
  name: emea_data_relay
  rest_endpoint: "https://localhost:8444"
  flight_endpoint: "https://localhost:50052"
  x509_cert_file: ./deploy/development/emea_data_relay/client_cert.pem
---
api_version: v1alpha1
kind: PeerRelay
spec:
  name: apac_data_relay
  rest_endpoint: "https://localhost:8445"
  flight_endpoint: "https://localhost:50053"
  x509_cert_file: ./deploy/development/apac_data_relay/client_cert.pem